Simple Task Manager
Shiveshtrivedi/React-Training pull request #2
Opened 2024-07-26 14:58 UTC by Shiveshtrivedi

Adding date when task is created - done
Sorting functionality - done
CSS of box  - done
Remove alert and show message on popup window - done
Naming convention - done
Document formatted by prettier - done
Remove console - done
Remove icon and use Unicode - done
Used arrow function only - done

2024-07-31 08:56 UTC, aakash-soni1 requested changes

2024-07-31 08:56 UTC, aakash-soni1 commented on task_management/data_file.js
> +export const url = "https://66a0bb4b7053166bcabc8698.mockapi.io/Data";
Give spacing in between new function  and variables

2024-07-31 08:56 UTC, aakash-soni1 commented on task_management/index.css
> +body {
Don't use rem and em use value in px

2024-07-31 08:56 UTC, aakash-soni1 commented on task_management/index.css
> +  z-index: 1000;
why you have used z-index 1000

2024-07-31 08:56 UTC, aakash-soni1 commented on task_management/index.css
> +@media (max-width: 480px) {
put media queries at the top of file

2024-07-31 08:56 UTC, aakash-soni1 commented on task_management/index.html
> +    <title>Document</title>
Give the proper Title

2024-07-31 11:50 UTC, Shiveshtrivedi commented on task_management/index.css
> +  z-index: 1000;
Just wanted that popup window visible over whole screen

2024-08-01 06:09 UTC, aakash-soni1 requested changes

2024-08-01 06:09 UTC, aakash-soni1 commented on package.json
> +    "globals": "^15.8.0",
Why have you use global as dependencies ?

2024-08-01 06:09 UTC, aakash-soni1 commented on task_management/index.js
> +    if (nameA > nameB) return ascending ? 1 : -1;
Why two conditions are there for same things, does the two condition is doing same thing or different ?

2024-08-01 06:09 UTC, aakash-soni1 commented on task_management/index.js
> +    if (nameA > nameB) return ascending ? 1 : -1;
find a optimize way to do this logic

2024-08-05 06:18 UTC, merged